##This is caller workflow.

name: microservice-1-workflow
on:
    workflow_dispatch:
jobs:
    call-build-job:
        name: Call Reusable build
        uses: chbhanupriya3/i27academy-devops-actions/.github/workflows/i27-microservices-workflow.yaml@main
