name: Schedule event
on:
    schedule:
      - cron:    '*/1 * * * *'    
jobs:
    schedule-job:
        runs-on: ubuntu-latest
        steps:
        -   name: Print schedule info
            run: echo "Using scheduler"    

        