name: List of files availability
on:
  workflow_dispatch:
jobs:
    list-files:
        runs-on: ubuntu-latest
        steps:
        -   name: Path location
            run:   |
                echo "current working dir"          
                pwd
        -   name: List of files
            run: |
                echo "List of filres in repo"        
                ls -R