name: Without Actions
on:
  workflow_dispatch:
jobs:
    manual-setup:
        runs-on: ubuntu-latest
        steps:
        -   name: Manually cloning the repo
            run: |
                echo "cloning the repo"          
                git clone https://github.com/${{github.repository}}.git
                echo "list of files after clone"
                ls -la
                pwd
        -   name:   Java Default Version
            run:    java -version || echo "Java is not installed"