name: Workflow1
on:
  workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        -   name: print name
            run: |
                echo "Actor is: ${{github.actor}}"        
                echo "Commit SHA is: ${{github.sha}}"
        -   name: step 2
            run: |
                echo "Intentionally failing this"
                exit 1     